"""
SOP generator — takes the analysis output and produces:

1. A weekly SOP markdown file with:
   - Top tweet breakdown (format, emotion, result)
   - Extracted frameworks
   - 14-tweet batch ready to post (7 standalone + 2 threads)
   - Posting schedule for the week

2. A tweet_batch.md with copy-paste ready tweets

All content is generated by Claude using the patterns found in the analysis.
"""

import json
import logging
import os
from datetime import datetime

import anthropic

from config import MODEL, YOUR_NICHE, YOUR_AUDIENCE, YOUR_TONE, OUTPUT_DIR
from memory import get_memory_context, save_week_snapshot

log = logging.getLogger(__name__)
client = anthropic.Anthropic()


def _build_sop_prompt(analysis: dict, week_number: int) -> str:
    patterns = analysis.get("patterns", {})
    top_tweets = analysis.get("top_tweets", [])
    opportunity = analysis.get("this_week_opportunity", "")
    contrarian = analysis.get("contrarian_observations", [])

    top_tweets_summary = ""
    for t in top_tweets[:5]:
        top_tweets_summary += (
            f"\n• @{t.get('author', '?')} — Format: {t.get('format', '?')} | "
            f"Emotion: {t.get('emotion_triggered', '?')} | "
            f"Hook: {t.get('hook_type', '?')}\n"
            f"  Steal: {t.get('steal_factor', '?')}\n"
        )

    return f"""You are an expert X (Twitter) content strategist and ghostwriter.

NICHE: {YOUR_NICHE}
AUDIENCE: {YOUR_AUDIENCE}
TONE: {YOUR_TONE}

This is Week {week_number} of building in public.
The account owner has $0 in digital product sales so far and is documenting the journey from zero.

RESEARCH FROM THIS WEEK'S TOP TWEETS:

Top performing tweet frameworks:
{top_tweets_summary}

Dominant content patterns:
- Top formats: {", ".join(patterns.get("dominant_formats", []))}
- Top emotions: {", ".join(patterns.get("dominant_emotions", []))}
- Top hooks: {", ".join(patterns.get("dominant_hooks", []))}

What gets shared: {patterns.get("what_gets_shared", "")}
What converts: {patterns.get("what_converts", "")}
Niche insights: {patterns.get("niche_specific_insights", "")}

Contrarian findings: {"; ".join(contrarian)}

BIGGEST OPPORTUNITY THIS WEEK: {opportunity}

---

Using ALL of the above research, generate a complete weekly content SOP in markdown.

Include these exact sections:

# Week {week_number} Content SOP
## Research Summary (3-5 bullet points on what worked this week)
## Top 5 Tweet Frameworks (table: Framework | Emotion | Hook Type | Why It Works)
## This Week's Angle (based on the biggest opportunity identified)

## 7 Standalone Tweets
For each tweet include:
- Tweet number and sub-topic
- Format label
- Emotion triggered
- The tweet text (ready to copy-paste, no quotation marks around it)
- One line on why this will work

## Thread 1 — Build in Public (7 tweets)
Week {week_number} build-in-public thread. Honest, no income claimed (account is at Day {week_number * 7}).
Reference specific actions taken (building products, writing copy, setting up funnels).
Tweet 1 is the hook. Tweets 2-6 are value. Tweet 7 has a CTA to follow.

## Thread 2 — Framework/Tutorial Thread (7 tweets)
A deep-dive on the biggest opportunity identified this week.
Tweet 1 is the hook. Tweets 2-6 deliver the framework. Tweet 7 has a soft CTA.

## Posting Schedule (table: Day | Content | Time | Notes)

## Claude Prompt to Generate More Tweets Like These
Include a ready-to-use Claude prompt the user can run to generate 10 more tweets
in the same style as the top performers this week.

## Next Week: What to Watch
3 bullet points on trends or angles to monitor for next week's research.

---
Make all tweet text direct, punchy, and in this tone: {YOUR_TONE}.
All tweets must be under 280 characters unless they are thread tweets (which can be longer).
Do NOT add quotation marks around tweet text.
Do NOT include placeholder brackets like [X] or [your result] — write specific, complete tweets.
For the build-in-public thread, use realistic specifics for Week {week_number} of a zero-to-first-sale journey."""


def _build_tweet_batch_prompt(analysis: dict, week_number: int) -> str:
    """Separate prompt to generate a clean copy-paste tweet file."""
    patterns = analysis.get("patterns", {})
    opportunity = analysis.get("this_week_opportunity", "")

    return f"""You are a ghostwriter for an X account in this niche: {YOUR_NICHE}
Audience: {YOUR_AUDIENCE}
Tone: {YOUR_TONE}
Account status: Week {week_number}, building in public from $0, documenting the journey.

This week's research shows the top formats are: {", ".join(patterns.get("dominant_formats", []))}
The biggest opportunity: {opportunity}

Generate a clean tweet batch file with exactly:
- 7 standalone tweets (copy-paste ready, under 280 chars each)
- 2 threads (7 tweets each, with TWEET 1, TWEET 2 etc labels)

Label each tweet clearly. No preamble, no analysis — just the tweets.
Make them specific and complete — no placeholder brackets.
Build-in-public thread must reference real Week {week_number} activities (building products, testing copy, etc).
Tutorial thread must teach a specific Claude AI framework for building digital products."""


def generate_weekly_sop(analysis: dict, week_number: int) -> tuple[str, str]:
    """
    Generate the full SOP + tweet batch.
    Returns (sop_path, tweet_batch_path).
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")

    # --- Save to memory before generating ---
    log.info("Saving week snapshot to memory...")
    save_week_snapshot(week, analysis)

    # --- Generate full SOP ---
    log.info("Generating weekly SOP...")
    sop_content = ""
    sop_prompt = _build_sop_prompt(analysis, week_number)

    with client.messages.stream(
        model=MODEL,
        max_tokens=12000,
        thinking={"type": "adaptive"},
        system=(
            "You are an expert X (Twitter) content strategist. "
            "You write in markdown. You create practical, actionable content SOPs. "
            "Your tone is direct and no-nonsense."
        ),
        messages=[{"role": "user", "content": sop_prompt}],
    ) as stream:
        for event in stream:
            if (
                event.type == "content_block_delta"
                and event.delta.type == "text_delta"
            ):
                chunk = event.delta.text
                sop_content += chunk
                print(chunk, end="", flush=True)
        print()

    sop_path = os.path.join(OUTPUT_DIR, f"week_{week_number:02d}_sop_{date_str}.md")
    with open(sop_path, "w", encoding="utf-8") as f:
        f.write(f"# Week {week_number} X Account SOP\n")
        f.write(f"_Generated: {datetime.now().strftime('%B %d, %Y')}_\n\n")
        f.write("---\n\n")
        f.write(sop_content)
        f.write("\n\n---\n")
        f.write("_Auto-generated by X Account Bot — based on real niche research._\n")
    log.info(f"SOP saved: {sop_path}")

    # --- Generate clean tweet batch ---
    log.info("Generating tweet batch...")
    batch_content = ""
    batch_prompt = _build_tweet_batch_prompt(analysis, week_number)

    with client.messages.stream(
        model=MODEL,
        max_tokens=6000,
        messages=[{"role": "user", "content": batch_prompt}],
    ) as stream:
        for event in stream:
            if (
                event.type == "content_block_delta"
                and event.delta.type == "text_delta"
            ):
                chunk = event.delta.text
                batch_content += chunk
                print(chunk, end="", flush=True)
        print()

    batch_path = os.path.join(OUTPUT_DIR, f"week_{week_number:02d}_tweets_{date_str}.md")
    with open(batch_path, "w", encoding="utf-8") as f:
        f.write(f"# Week {week_number} Tweet Batch\n")
        f.write(f"_Generated: {datetime.now().strftime('%B %d, %Y')}_\n\n")
        f.write("---\n\n")
        f.write(batch_content)
    log.info(f"Tweet batch saved: {batch_path}")

    # --- Save raw analysis as JSON for reference ---
    analysis_path = os.path.join(OUTPUT_DIR, f"week_{week_number:02d}_analysis_{date_str}.json")
    with open(analysis_path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2, ensure_ascii=False)
    log.info(f"Raw analysis saved: {analysis_path}")

    return sop_path, batch_path
