"""
SOP generator — takes the analysis output and produces:

1. A weekly SOP markdown file with:
   - Top tweet breakdown (format, emotion, result)
   - Extracted frameworks
   - 25-tweet batch ready to post (5 per day, Mon–Fri)
   - Posting schedule for the week

2. A tweet_batch.md with copy-paste ready tweets

All content is generated by Claude using the patterns found in the analysis.
"""

import json
import logging
import os
from datetime import datetime

import anthropic

from config import MODEL, YOUR_NICHE, YOUR_AUDIENCE, YOUR_TONE, OUTPUT_DIR
from memory import get_memory_context, save_week_snapshot

log = logging.getLogger(__name__)
client = anthropic.Anthropic()


def _build_sop_prompt(analysis: dict, week_number: int) -> str:
    patterns = analysis.get("patterns", {})
    top_tweets = analysis.get("top_tweets", [])
    opportunity = analysis.get("this_week_opportunity", "")
    contrarian = analysis.get("contrarian_observations", [])

    top_tweets_summary = ""
    for t in top_tweets[:5]:
        top_tweets_summary += (
            f"\n• @{t.get('author', '?')} — Format: {t.get('format', '?')} | "
            f"Emotion: {t.get('emotion_triggered', '?')} | "
            f"Hook: {t.get('hook_type', '?')}\n"
            f"  Steal: {t.get('steal_factor', '?')}\n"
        )

    return f"""You are an expert X (Twitter) content strategist and ghostwriter.

NICHE: {YOUR_NICHE}
AUDIENCE: {YOUR_AUDIENCE}
TONE: {YOUR_TONE}

This is Week {week_number} of building in public.
ACCOUNT STATUS: ~3 followers, 1 tweet posted, 8 replies. Pure Day 0 build-in-public energy.
Strategy: zero authority posturing. Raw honesty, specific numbers, real actions taken.
No income claims. No "I made $X" unless from business log. Document the process, not the results yet.

{get_memory_context(week_number)}

RESEARCH FROM THIS WEEK'S TOP TWEETS:

Top performing tweet frameworks:
{top_tweets_summary}

Dominant content patterns:
- Top formats: {", ".join(patterns.get("dominant_formats", []))}
- Top emotions: {", ".join(patterns.get("dominant_emotions", []))}
- Top hooks: {", ".join(patterns.get("dominant_hooks", []))}

What gets shared: {patterns.get("what_gets_shared", "")}
What converts: {patterns.get("what_converts", "")}
Niche insights: {patterns.get("niche_specific_insights", "")}

Contrarian findings: {"; ".join(contrarian)}

BIGGEST OPPORTUNITY THIS WEEK: {opportunity}

---

Using ALL of the above research, generate a complete weekly content SOP in markdown.

Include these exact sections:

# Week {week_number} Content SOP
## Research Summary (3-5 bullet points on what worked this week)
## Top 5 Tweet Frameworks (table: Framework | Emotion | Hook Type | Why It Works)
## This Week's Angle (based on the biggest opportunity identified)

## 15 Tweets — 3 Per Day, Mon–Fri (8am, 1pm, 6pm EST)

Generate exactly 15 tweets total. Mix formats naturally across the week.
Include 1 thread worked naturally into the schedule (not forced).
No character limit — this account has X Premium.

For each standalone tweet include:
- Tweet number and sub-topic
- Format label
- The tweet text (ready to copy-paste, no quotation marks)

Threads: label with THREAD A or THREAD B and include 5–8 tweets each.
Thread 1: Build in Public — Week {week_number} honest update. Real actions, no income claims unless from business log.
Thread 2: Framework/Tutorial — teach a specific Claude AI technique or digital product strategy.

## Posting Schedule (table: Day | Slot | Content Type | Time EST)

## Claude Prompt to Generate More Tweets Like These
Include a ready-to-use Claude prompt the user can run to generate 10 more tweets
in the same style as the top performers this week.

## Next Week: What to Watch
3 bullet points on trends or angles to monitor for next week's research.

---
Make all tweet text direct, punchy, and in this tone: {YOUR_TONE}.
No character limit — X Premium account, tweets can be as long as needed.
Do NOT add quotation marks around tweet text.
Do NOT include placeholder brackets like [X] or [your result] — write specific, complete tweets.
For build-in-public content: Week {week_number}, ~3 followers, zero sales so far. Pure raw honesty wins.
If business log entries exist above, reference those real details in the build-in-public content."""


def _build_tweet_batch_prompt(analysis: dict, week_number: int) -> str:
    """Separate prompt to generate a clean copy-paste tweet file."""
    patterns = analysis.get("patterns", {})
    opportunity = analysis.get("this_week_opportunity", "")

    from memory import get_memory_context, get_business_log, get_personal_profile
    profile = get_personal_profile()
    business_entries = get_business_log(last_n=10)

    # Build business context — only include if real data exists
    business_context = ""
    if business_entries:
        business_context = "\n\nREAL BUSINESS UPDATES (use ONLY these for any personal metrics):\n"
        for e in business_entries:
            business_context += f"  [{e.get('date', '?')}] {e['text']}\n"
        business_context += "\nOnly reference numbers, products, and outcomes explicitly stated above."
    else:
        business_context = "\n\nNO BUSINESS LOG DATA YET — Week 1, zero sales, no products launched, no metrics to report. Do NOT invent any."

    # Build profile context
    profile_context = ""
    if profile:
        profile_context = f"""
ACCOUNT OWNER — write FROM this person's perspective:
- Name: {profile.get('name', 'Anthony')}
- Age: {profile.get('age', '26')}, from {profile.get('location', 'Philadelphia, PA')}
- Background: {profile.get('background', '')}
- Why they started: {profile.get('why_started', '')}
- What they're building: {profile.get('the_bot', '')}
- Real struggles: {profile.get('struggles', '')}
- Goals: {profile.get('goals', '')}
Use these personal details to make build-in-public content feel like it came from a real human, not a brand.
"""

    return f"""You are a world-class copywriter and ghostwriter for an X (Twitter) account.

Niche: {YOUR_NICHE}
Audience: {YOUR_AUDIENCE}
Tone: {YOUR_TONE}
Account: Week {week_number}, 3 followers, 0 sales, building from scratch in public.
No character limit — X Premium account.
{profile_context}
This week's research — top formats: {", ".join(patterns.get("dominant_formats", []))}
Biggest opportunity: {opportunity}
{business_context}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ABSOLUTE RULES — NEVER BREAK THESE:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. ZERO FABRICATION — Never invent stats, follower counts, likes, sales, products, income, or any metric not explicitly provided in the business log above. If no data exists, write around it with pure value or honest vulnerability. No exceptions.
2. NO PLACEHOLDERS — No [your result], [X followers], [insert number]. Every word must be real and complete.
3. WEEK 1 REALITY — This person has 3 followers and zero sales. Don't write as if they have authority they haven't earned yet. The authority comes from the VALUE of the information, not a claimed track record.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
COPYWRITING STANDARDS — EVERY TWEET:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Use human psychology levers strategically:
- CURIOSITY GAP: Open a loop in the first line that the reader must close (never reveal the full picture upfront)
- IDENTITY THREAT: Challenge a belief the reader holds about themselves ("If you're still doing X, you're leaving money on the table")
- FUTURE PACING: Paint a vivid before/after that makes the reader feel the transformation before they take action
- SPECIFICITY AS PROOF: Exact numbers, specific tools, precise steps — specificity signals credibility more than vague claims
- PATTERN INTERRUPT: Start with something that breaks the scroll — a counterintuitive statement, a raw confession, or an unexpected comparison
- SOCIAL EXCLUSIVITY: Frame the information as something most people don't know or won't share

The writing must be so good people can't believe it's free. Think: "I can't believe someone just gave this away."
Write like a 26-year-old from Philly who figured something out and can't stop talking about it — not like a marketer.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WEEK 1 CONTENT STRATEGY:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Since there's no performance data yet, Week 1 content = establish WHY people should follow this account.

CONTENT PILLARS for this week:
- 35% Outside-the-box Claude money-making ideas nobody is talking about (not "write blog posts" — think creative, specific, underutilized use cases that make people go "wait, you can do that?")
- 25% Personal story / raw journey (use the profile above — the Philly background, the failed careers, the first digital dollar in 2025, the consistency struggle — make it relatable and real)
- 20% Hot takes / contrarian opinions (challenge a popular belief in the niche confidently)
- 20% Thread (one educational deep-dive, one build-in-public update)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
THE BOT TEASE — use 1–2 times this week:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Anthony is building an X automation bot that handles research, content generation, and posting automatically.
He's going to give it away for FREE to his followers.
Tease this 1–2 times across the week — create curiosity and make people want to follow to get access.
Example angles: "I'm building something that does everything I just described automatically. Going to give it away free. Follow to get it first." — keep it vague and exciting, not a full reveal.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CTAs — add to 2–3 high-value tweets:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
End 2–3 of the best value tweets with a soft CTA. Examples:
- "I'm putting this into a free guide for anyone who follows. Drop a 🔥 and I'll DM it to you."
- "Building this into a free resource. Follow so you don't miss it when I drop it."
- "This is going into the free bot I'm giving away. More details soon — follow to stay in the loop."
CTAs must feel organic and generous, never salesy. The offer is always FREE.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OUTPUT — exactly 15 tweets (3 per day, Mon–Fri):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Mix: 11–13 standalone tweets + 1 thread (5–7 tweets). Thread counts as one day slot.
Spread pillars naturally — no two same-pillar tweets back to back.

FORMAT:
## STANDALONE TWEETS

**STANDALONE 1** (Hot Take)
[tweet text]

**STANDALONE 2** (Personal Story)
[tweet text]

... up to STANDALONE 13

## THREAD 1 — [Title]

**TWEET 1**
[hook]

**TWEET 2**
[body]

... 5–7 tweets total

Label each clearly. No preamble, no analysis — just the tweets, ready to post.
Every tweet must be complete, specific, and so good it could go viral on its own."""


def generate_weekly_sop(analysis: dict, week_number: int) -> tuple[str, str]:
    """
    Generate the full SOP + tweet batch.
    Returns (sop_path, tweet_batch_path).
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")

    # --- Save to memory before generating ---
    log.info("Saving week snapshot to memory...")
    save_week_snapshot(week_number, analysis)

    # --- Generate full SOP ---
    log.info("Generating weekly SOP...")
    sop_content = ""
    sop_prompt = _build_sop_prompt(analysis, week_number)

    with client.messages.stream(
        model=MODEL,
        max_tokens=12000,
        thinking={"type": "adaptive"},
        system=(
            "You are an expert X (Twitter) content strategist. "
            "You write in markdown. You create practical, actionable content SOPs. "
            "Your tone is direct and no-nonsense."
        ),
        messages=[{"role": "user", "content": sop_prompt}],
    ) as stream:
        for event in stream:
            if (
                event.type == "content_block_delta"
                and event.delta.type == "text_delta"
            ):
                chunk = event.delta.text
                sop_content += chunk
                print(chunk, end="", flush=True)
        print()

    sop_path = os.path.join(OUTPUT_DIR, f"week_{week_number:02d}_sop_{date_str}.md")
    with open(sop_path, "w", encoding="utf-8") as f:
        f.write(f"# Week {week_number} X Account SOP\n")
        f.write(f"_Generated: {datetime.now().strftime('%B %d, %Y')}_\n\n")
        f.write("---\n\n")
        f.write(sop_content)
        f.write("\n\n---\n")
        f.write("_Auto-generated by X Account Bot — based on real niche research._\n")
    log.info(f"SOP saved: {sop_path}")

    # --- Generate clean tweet batch ---
    log.info("Generating tweet batch...")
    batch_content = ""
    batch_prompt = _build_tweet_batch_prompt(analysis, week_number)

    with client.messages.stream(
        model=MODEL,
        max_tokens=12000,
        messages=[{"role": "user", "content": batch_prompt}],
    ) as stream:
        for event in stream:
            if (
                event.type == "content_block_delta"
                and event.delta.type == "text_delta"
            ):
                chunk = event.delta.text
                batch_content += chunk
                print(chunk, end="", flush=True)
        print()

    batch_path = os.path.join(OUTPUT_DIR, f"week_{week_number:02d}_tweets_{date_str}.md")
    with open(batch_path, "w", encoding="utf-8") as f:
        f.write(f"# Week {week_number} Tweet Batch\n")
        f.write(f"_Generated: {datetime.now().strftime('%B %d, %Y')}_\n\n")
        f.write("---\n\n")
        f.write(batch_content)
    log.info(f"Tweet batch saved: {batch_path}")

    # --- Save raw analysis as JSON for reference ---
    analysis_path = os.path.join(OUTPUT_DIR, f"week_{week_number:02d}_analysis_{date_str}.json")
    with open(analysis_path, "w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2, ensure_ascii=False)
    log.info(f"Raw analysis saved: {analysis_path}")

    return sop_path, batch_path
